logging:
    level:
        org:
            springframework: DEBUG

spring:
    config:
        activate:
            on-profile: dev

    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/inspire
        username: root
        password: akfldkqlqjs

    jpa:
        hibernate:
            ddl-auto: none  # create, create_drop, update, none
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect
                format_sql: true

    ai:
        openai:
            model: ${OPEN_AI_MODEL}
            api:
                key: ${OPEN_AI_KEY}
                url: ${OPEN_AI_URL}

jwt:
    secret: ${JWT_SECRET_KEY}